#	CrisTreeCapitator Test Configuration File

#Este valor sirve para matarlos
qkjrnls: 115
esto es un entero: 115
esto es un string: String
#Este valor sirve para matarlos
esto es un algo: 115
esto es un booleano: true
esto es un real: 3.141592653589793
#Este valor sirve para saludar
esto es un string de saludar: hola a todos
