name: CrisTreeCapitator
main: main.TreeCapitator
version: 6.0
api-version: 1.13
softdepend: [WorldGuard]
commands:
  tc:
   description: Controls CrisTreeCapitator and gives information.
   aliases: [treecapitator, treecap]
   usage: /tc help
   
permissions:
  cristreecapitator.*:
    description: Gives access to all Cristichi's Tree Capitator commands
    children:
      cristreecapitator.admin: true
      cristreecapitator.use: true
      cristreecapitator.vip: true
  cristreecapitator.admin:
    description: Allows you to change config values and update
    default: op
  cristreecapitator.use:
    description: Allows you to cut down trees at once
    default: true
  cristreecapitator.vip:
    description: Allows you to cut down trees at once even if VIP MODE is enabled
    default: false