name: CrisTreeCapitator
main: main.TreeCapitator
version: ALPHA
commands:
  tc:
   description: Control CrisTreeCapitator and extra info.
   aliases: [treecapitator, treecap]
   usage: /tc help 
   
permissions:
  cristreecapitator.*:
    description: Gives access to all Cristichi's Tree Capitator commands
    children:
      cristreecapitator.admin: true
      cristreecapitator.use: true
      cristreecapitator.vip: true
  cristreecapitator.admin:
    description: Allows you to change config values and update
    default: op
  cristreecapitator.use:
    description: Allows you to cut down trees at once
    default: true
  cristreecapitator.vip:
    description: Allows you to cut down trees at once when VIP MODE is enabled
    default: false